version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    restart: always
    container_name: nodered
    ports:
      - "1880:1880"
    environment:
      - MYSPECIALTOKEN=${TOKEN}
    volumes:
      - ./nodered_data:/data

volumes:
  nodered_data:

